version: '2'

services:
  certbot:
    build: .
    container_name: certbot
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - letsencrypt:/etc/letsencrypt
    restart: unless-stopped
    environment:
      - COMMON_ARGS=certonly --agree-tos --non-interactive --keep-until-expiring --email admin@laurent.sh --standalone --preferred-challenges http
      - LOOP_ARGS=-d seed.laurent.sh | -d laurent.sh,www.laurent.sh | -d git.laurent.sh
      - DOCKER_HOTS=unix:///var/run/docker.sock
      - NGINX_PROXY_CONTAINER=nginx
